# Generated by Django 5.1.3 on 2024-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nota1', models.IntegerField()),
                ('nota2', models.IntegerField()),
                ('nota3', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateField()),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
    ]
