# Generated by Django 5.1.3 on 2024-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumnos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='nota1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nota2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nota3',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
