# Generated by Django 5.1.3 on 2024-11-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_remove_alumnos_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='carrera',
            field=models.CharField(default='Sin carrera', max_length=50),
        ),
    ]
